### ISSUE TITLE
Slimes are basically unstoppable, especially in outbreaks

### ISSUE THREAD

**Issue by BlueNexus** [sshado/Aphelion-Code#103]
I'm sure you're all aware of the situation. There are slime outbreaks multiple times a day, which even ERT's with firefighter mechs can't contain. Freeze rays used to be one-hit kills on slimes, you can now unload an entire gun into them and do seemingly no damage. I personally splashed an adult slime with 500u of water and they didn't die. Fire extinguishers do basically nothing. 

All of this means that slime outbreaks are basically unstoppable, causing half of the station to die to slimes while the only defences against them fail due to an oversight on the part of baystation. I don't care if this was by design, as something baystation decided to do. It's awful, and it needs to stop.

Slimes needs to take as much damage from fire extinguishers, water and other sources as they used to. otherwise, we're going to continue having gamebreaking slime outbreaks over and over again. This ruins the gameplay experience, as it's basically a threat that keeps re-occuring, and there's nothing the station can do to stop it. 

If nothing can be done, then the only solutions are to either put a super-powerful sprinkler system in place in xenobiology, or temporarily prevent the job from being selected. This has gone too far.

**Comment by Isratosh** [comment]
I'm killing a slime with two fire extinguisher sprays. What seems to be the problem?

**Comment by Lorwp** [comment]
I’ll test if it's on the latest Commit in a moment

**Comment by Lorwp** [comment]
@BlueNexus Isratosh Seems to be Correct, i can easily Kill them in testing.
