### ISSUE TITLE
Travis Is broken

### ISSUE THREAD

**Issue by Lorwp** [sshado/Aphelion-Code#117]
As the Title Says, Travis is Broken, Any job (Completed successfully or not) shows up as a Failed Job.
[Relevant Log](https://gist.github.com/Lorwp/1cfa885da78647aab6be) and [My Fork's attempted Compile](https://travis-ci.org/Lorwp/Aphelion-Code/builds/78542098)

**Comment by BlueNexus** [comment]
This is due to an error with travis being unable to locate baystation12.int, as it doesn't actually exist on the git. You can still look for any compile errors by clicking the X mark, though. It would be worth trying to get travis working properly, however. It's a very useful tool.

**Comment by BlueNexus** [comment]
Fixed.

**Comment by Lorwp** [comment]
@BlueNexus Good job.
