### ISSUE TITLE
SM IS BROKEN (GAME BREAKING)

### ISSUE THREAD

**Issue by WkSavage** [sshado/Aphelion-Code#136]
Apparently all of the piping is fucked and the SM cannot cool its self even at //LOW POWER//. This is game breaking

**Comment by WkSavage** [comment]
@BlueNexus  please set this as a critical problem

**Comment by Isratosh** [comment]
This literally isn't a problem. I'm testing this on the server right now and it's working fine. The setup is exactly the same in concept as the previous two designs.

**Comment by BlueNexus** [comment]
@Isratosh Then we need to make that clear to players. Closing issue for now, but make it very clear that you set it up the same way.
