### ISSUE TITLE
Gitter.im

### ISSUE THREAD

**Issue by Lorwp** [sshado/Aphelion-Code#157]
Recently i noticed that [Gitter](https://gitter.im) exists, i've played around with it at a channel for my private repo ([![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Lorwp/Aphelion-Code?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)) and i think it looks pretty cool. I'm making an issue to see if anyone else thinks it's as cool as i do.

It has a few things that make it slightly better than skype:
- [Full GitHub Flavored Markdown support](https://gitter.zendesk.com/hc/en-us/articles/200176682-Markdown-basics) (And line breaks with shift+enter or [compose mode](https://gitter.zendesk.com/hc/en-us/articles/201302311-Compose-mode)
- [Integration](https://gitter.zendesk.com/hc/en-us/articles/200176722-Integrations) (E.g, whole channel gets notified of Pull requests or Travis jobs)
- [Lurk mode](https://gitter.zendesk.com/hc/en-us/articles/200227021-Lurk-mode) with `/lurk`
- As Shown above, a README badge
- [Message Editing](https://gitter.zendesk.com/hc/en-us/articles/200296302-Editing-messages) (For five minutes after sending)
- [Issue and Pull request Mentions](https://gitter.zendesk.com/hc/en-us/articles/200176692-Issue-and-Pull-Request-mentions)
- [Support For connecting with IRC](https://irc.gitter.im/)
- Quote people with Alt+click (E.g, `:point_up: [September 9, 2015 3:03 PM](https://gitter.im/Lorwp/Aphelion-Code?at=55efbda3760979e727e93801)` turns into :point_up: [September 9, 2015 3:03 PM](https://gitter.im/Lorwp/Aphelion-Code?at=55efbda3760979e727e93801))

Just [Register with Github](https://gitter.im) and [Try it out](https://gitter.im/Lorwp/Aphelion-Code?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

_or complain on how i sound like i'm advertising this_

**Comment by BlueNexus** [comment]
It might be worth taking a look at. Most development teams for SS13 use a botted IRC, but we will see how this turns out.

**Comment by Lorwp** [comment]
@BlueNexus It is possible to use bots with gitter, as shown with [hubot-gitter2](https://github.com/huafu/hubot-gitter2). As mentioned above, there is also a [IRC](https://irc.gitter.im) [bridge](https://github.com/gitterHQ/irc-bridge) if it's more convient to use IRC, though i am not sure how something like markdown would be represented when outputted to IRC.

**Comment by BlueNexus** [comment]
@Lorwp I see. https://gitter.im/sshado/Aphelion-Code Try this, tell me how it looks.

**Comment by Lorwp** [comment]
It works fine, i'll keep this issue open just in case of any issues, at least until it's used more often

**Comment by Isratosh** [comment]
We're using this now.
