### ISSUE TITLE
Spiders are unstoppable

### ISSUE THREAD

**Issue by DJPantheris** [sshado/Aphelion-Code#215]
When the Giant Spiders attacked, I repeatedly tried to smash one with a toolbox, unfortunately despite me giving it the ultimate smackdown, the spider still lived, even with Flux beating the shit out of it too.  They seem to have extreme amounts of health, resulting in unstoppable spiders which the crew is not able to stop.

**Comment by BlueNexus** [comment]
Not an issue. You shouldn't be trying to fight an enormous, deadly spider, unless you're security.
