### ISSUE TITLE
Antagonist Ban link from Jobban pannel

### ISSUE THREAD

**Issue by Eveningshadow** [sshado/Aphelion-Code#217]
You are unable to ban a player from all antagonist positions.  Clicking on the Antagonist link only adds one antagonist "job" to the ban list.

**Comment by BlueNexus** [comment]
You can. I know, because i've done it. Click on the heading for the antagonist area, aka a "syndicate" ban.

**Comment by Eveningshadow** [comment]
Kaed and i both tried it last night and it only adds one antag job to the ban.  Referance ckey bigmeme as an example.

**Comment by BlueNexus** [comment]
If it adds the job "Syndicate" that's fine. That bans them from all traitor roles.
