### ISSUE TITLE
Machine var doesnt reset

### ISSUE THREAD

**Issue by BlueNexus** [sshado/Aphelion-Code#38]
When DCing and reconnecting, or seemingly at random, the machine var does not reset, leaving the player unable to move. A simple fix for this would be to have logout reset the machine var to null. I would do this myself, but im not at home.

**Comment by DJPantheris** [comment]
Hmmm try checking the routines that assign the machine var to the characters they're playing.  I have a suspicion that you might find it there.  It's a shot in the dark but I'm willing to bet that's where the issue may lie.  I'll take a look at it myself if you have some idea where to look, Cirra.  It may be a shot in the dark but it's better than nothing.

**Comment by BlueNexus** [comment]
The issue is that the machine var isn't removed when you stop using certain machines. I can fix it, i'm just a little busy with PDA slots right now

**Comment by DJPantheris** [comment]
Oh okay so I'm going to be looking for it where SS13 assigns the machine var to the player using said machine?  Any clue what file that's in?

**Comment by Ryan784** [comment]
I made a fix for it, but as I don't know what's actually causing the bug or how to recreate it, I can't actually bugtest it as of yet. I'll pull the changes anyway.

**Comment by Isratosh** [comment]
This bug is rather minor. Any admin with varedit can fix it. I'll see if Ryan's fix worked and close this later.

**Comment by BlueNexus** [comment]
Changed to major. This issue regularly causes people to be stuck in the camera view or interface for some machines, leaving them helpless without an admin.

**Comment by DJPantheris** [comment]
Changed to critical because it's gamebreaking for players and persists between restarts of the client.

**Comment by BlueNexus** [comment]
As a reminder, this issue is marked as critical, and should be the current priority. If this hasnt already been fixed when you look at it, please work on a fix.

**Comment by BlueNexus** [comment]
I'd like some confirmation that it's fixed with the update.

**Comment by Ryan784** [comment]
Fixed.
