### ISSUE TITLE
Robolimb surgery issue

### ISSUE THREAD

**Issue by BlueNexus** [sshado/Aphelion-Code#39]
In order to attach a full robotic leg, you must currently target the nonexistant foot. This has caused several fatalities in game, as surgeons struggle to find an attachment point. This should be changed so that you must target the leg, not the foot.

**Comment by DJPantheris** [comment]
I have no idea where to start looking.  I tried Surgery-attachlimb but that's been unincluded.  I tried the limb attachment method in the actual surgery module but that's also giving me no leads.

**Comment by DJPantheris** [comment]
If this isn't done in 4 days, I'll be escalating this one, since I have no idea where to look, I'll also be unassigning myself.

**Comment by Ryan784** [comment]
If you want to know where to look I'm pretty sure I've narrowed it down to:
code/modules/surgery/surgery.dm for a general look at surgery, and more specifically for limb reattachment:
code/modules/surgery/robolimbs.dm

If anyone wants to look into this today while I work on it, it's always appreciated. From what I can tell, this 'bug' almost appears to be on purpose.

**Comment by Ryan784** [comment]
Appears to have fixed itself..
