### ISSUE TITLE
Probability Redistribution

### ISSUE THREAD

**Issue by DJPantheris** [sshado/Aphelion-Code#41]
Change of random events list to re-distribute probabilities away from significantly harmful unavoidable events (space dust/rods) - Space dust does about as much damage as a meteor hitting the side of the station.  I have observed this.

**Comment by walmartcheapo** [comment]
Rods don't exist in the files anymore and space dust is a 3% chance as a minor event (very little damage anyway) and a 1% chance as a moderate event. It seems this has been done already.

**Comment by Isratosh** [comment]
Done.
