### ISSUE TITLE
Toggle Bomb Cap to OFF verb addition

### ISSUE THREAD

**Issue by DJPantheris** [sshado/Aphelion-Code#43]
Implementation of a Toggle Bombs Off button under the Secrets panel, to change bombcap to 0/0/0 (UT code) - How about make this a “Set Bomb Cap” verb?

**Comment by Isratosh** [comment]
I literally did this. Issues that are in italics on the issue tracker forum post are completed.

**Comment by Spoopy11** [comment]
Doesn't that bring about the question, why completed things are in italics, and not strike through.

**Comment by Isratosh** [comment]
It's described in the top of the forum thread that all issues in italics are completed.
