### ISSUE TITLE
HTML sanitizing on DNarrate/GNarrate/SMsg

### ISSUE THREAD

**Issue by DJPantheris** [sshado/Aphelion-Code#51]
Apparently HTML is being sanitized from these commands on a mob level or some other level I can't easily fix.  I tried checking the adminverbs but all they give me a lead to is that they push the message to the target.

**Comment by Isratosh** [comment]
Direct Narrate, Global Narrate and Subtle Message are not sanitized. I just tested this in game. However, the "make-sound" verb is sanitized, which needs to be fixed.

**Comment by Isratosh** [comment]
Fixed by #53
