### ISSUE TITLE
Inferior shield sprite in use

### ISSUE THREAD

**Issue by BlueNexus** [sshado/Aphelion-Code#59]
I understand that wer worked hard on the new shield, but it's honestly just bad. Revert it, please, then get a proper sprite.

**Comment by DJPantheris** [comment]
I just made one that's a little better but not best.  At least it LOOKS like a proper shieldgen.

**Comment by Lorwp** [comment]
Could a picture be attached to show the Sprite?

**Comment by Isratosh** [comment]
Done.
