### ISSUE TITLE
Flashes Blind AIs

### ISSUE THREAD

**Issue by DJPantheris** [sshado/Aphelion-Code#61]
Self explanatory.  I clicked on the flash in front of me in my chamber and ended up blinding myself.

**Comment by BlueNexus** [comment]
Set it to medium, seeing as this could cause major issues for any AI dealing with an intelicard-wielding intruder.

**Comment by DJPantheris** [comment]
Can you tell me what file to look in for flash effects?

**Comment by BlueNexus** [comment]
flick.flash() I think. It'd be in the flash.dm itself.

**Comment by DJPantheris** [comment]
Thank you I'll add a check to make sure the player isn't an AI then.
