### ISSUE TITLE
Coins take a minute to dissapear from inventory when used in machines

### ISSUE THREAD

**Issue by BlueNexus** [sshado/Aphelion-Code#62]
What it says on the tin. if you use a coin in a vending machine, it sticks around for about 30 seconds. However, this allows the player to vend as many items as they want during that time, pretty much for free. In other words, buy everything in the vending machine with one coin, if you're a fast enough clicker.

**Comment by BlueNexus** [comment]
A fix for this will be coming soon, along with a bunch of other fixes from baystation. Will be working more on porting the fixes tonight

**Comment by Ryan784** [comment]
So next bay update will fix this or does this still need to be fixed?

**Comment by BlueNexus** [comment]
The upcoming rebase fixes this.

**Comment by Ryan784** [comment]
Bug is fixed, please close.
