### ISSUE TITLE
"me" command is totally broken.

### ISSUE THREAD

**Issue by ghost** [sshado/Aphelion-Code#76]
Doesn't show the name of the emoting character, whereas say!action does.

**Comment by Isratosh** [comment]
For reference, http://imgur.com/m8m0J5Q. That's the output of a me command, nothing more than that. http://imgur.com/0H4gQkn is how it should look.

**Comment by ghost** [comment]
Furthermore, it appears spoken *emotes are entirely broken, too. Might be connected to Spark's *pingbuzzbeep.

**Comment by Spacemanspark** [comment]
If you completely reverted it, I doubt it.
Sorry if it was me, though. :/
Edit: Well fuck it was me.

**Comment by Isratosh** [comment]
Fixed by reverting #60 

Feel free to make another pull request with fixed code. Make sure you test it on your end first and post the results.

**Comment by Spacemanspark** [comment]
Yep, will do.
