### ISSUE TITLE
Research Overhaul

### ISSUE THREAD

**Issue by DJPantheris** [sshado/Aphelion-Code#92]
It seems the playerbase would like to see new items produced by research rather than researching stuff that already exists.  So I'm gonna divert a lot of time into that.  I'm also going to be needing a spriter and someone to bounce ideas off of.

**Comment by DJPantheris** [comment]
This will be done over on my fork and will be duplicated there.

**Comment by Isratosh** [comment]
you can safely ignore those two logs as I was pressing buttons that I shouldn't have pressed.

If you ever made any progress on this, I'd like to see a full changelog included. Everything that you've added or changed. Overhauling science is a big project and it needs to be documented.

**Comment by BlueNexus** [comment]
This should be a DNM pull request, not an issue.
